apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shopease-user-service
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: user-service
  endpoints:
    - targetPort: 8001
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shopease-order-service
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: order-service
  endpoints:
    - targetPort: 8002
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shopease-notification-service
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: notification-service
  endpoints:
    - targetPort: 8003
      path: /metrics
      interval: 15s
