apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ecommerce-microservices-user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ALGORITHM
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ACCESS_TOKEN_EXPIRE_MINUTES
            - name: REFRESH_TOKEN_EXPIRE_DAYS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REFRESH_TOKEN_EXPIRE_DAYS
            - name: SERVICE_NAME
              value: "user-service"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
