apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-scale-test
  namespace: prod
spec:
  replicas: 6
  selector:
    matchLabels:
      app: karpenter-scale-test
  template:
    metadata:
      labels:
        app: karpenter-scale-test
    spec:
      nodeSelector:
        workload-type: karpenter
      containers:
        - name: pause
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
