resources:
  - namespace.yaml
  - ../../base
namespace: staging

patches:
  - target:
      kind: Deployment
      name: user-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

  - target:
      kind: Deployment
      name: order-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

  - target:
      kind: Deployment
      name: notification-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
